name: today_weather
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  location: ^4.4.0
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  logging: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - .env